name: 'wealth_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'wealth_lakehouse'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  wealth_lakehouse:
    staging:
      +materialized: table
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
